#!/bin/sh
# /etc/init.d/runEasyPlayer
### BEGIN INIT INFO
# Provides:          easyPlayer
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

### sym link >>> /etc/init.d/runEasyPlayer
export PATH=$PATH:/usr/bin;

case "$1" in
start)
	LOG_FILE=/var/log/easyPlayer.log;
	exec 3>&1 4>&2;
	trap 'exec 2>&4 1>&3' 0 1 2 3;
	exec 1>${LOG_FILE} 2>&1;
	dt=$(date '+%d/%m/%Y %H:%M:%S');
	echo "$dt"
	sleep 20;
	easyPlayer &  #scriptarguments
;;
debug)
	easyPlayer -v 1 &  #scriptarguments
;;
stop)
	killall easyPlayer
	killall omxplayer.bin
	killall python3
;;
*)
	echo "Usage: /etc/init.d/runEasyPlayer {start|stop}"
	exit 1
;;
esac
exit 0